Repository dora-metrics/pelorus, pull requests merged in 2022-12, with the labels that each got.

#739 Fix pelorus-operator versioning within bundle
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
Labels: lgtm, dco-signoff: yes

#740 Deprecate Grafana snapshot job
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  charts/pelorus/templates/dashboard-snapshot-cronjob.yaml
  charts/pelorus/templates/grafana-post-install-hook.yaml
  charts/pelorus/templates/grafana.yaml
  charts/pelorus/values.yaml
  demo/tekton-demo-setup/tekton_demo_values.yaml
  docs/Install.md
Labels: approved, dco-signoff: yes

#741 Modified resources for the pelorus-operator
  pelorus-operator/Dockerfile
  pelorus-operator/Makefile
  pelorus-operator/bundle.Dockerfile
  pelorus-operator/bundle/manifests/pelorus-operator-controller-manager-metrics-service_v1_service.yaml
  pelorus-operator/bundle/manifests/pelorus-operator-manager-config_v1_configmap.yaml
  pelorus-operator/bundle/manifests/pelorus-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/bundle/metadata/annotations.yaml
  pelorus-operator/bundle/tests/scorecard/config.yaml
  pelorus-operator/config/default/kustomization.yaml
  pelorus-operator/config/default/manager_auth_proxy_patch.yaml
  pelorus-operator/config/default/manager_config_patch.yaml
  pelorus-operator/config/manager/controller_manager_config.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manager/manager.yaml
  pelorus-operator/config/prometheus/monitor.yaml
  pelorus-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  pelorus-operator/config/rbac/auth_proxy_role.yaml
  pelorus-operator/config/rbac/auth_proxy_role_binding.yaml
  pelorus-operator/config/rbac/auth_proxy_service.yaml
  pelorus-operator/config/rbac/leader_election_role.yaml
  pelorus-operator/config/rbac/leader_election_role_binding.yaml
  pelorus-operator/config/rbac/pelorus_editor_role.yaml
  pelorus-operator/config/rbac/pelorus_viewer_role.yaml
  pelorus-operator/config/rbac/role_binding.yaml
  pelorus-operator/config/rbac/service_account.yaml
  pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
  pelorus-operator/config/scorecard/patches/basic.config.yaml
  pelorus-operator/config/scorecard/patches/olm.config.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  pelorus-operator/helm-charts/pelorus/templates/dashboard-snapshot-cronjob.yaml
  pelorus-operator/helm-charts/pelorus/templates/grafana-post-install-hook.yaml
  pelorus-operator/helm-charts/pelorus/templates/grafana.yaml
  pelorus-operator/helm-charts/pelorus/values.yaml
  scripts/pelorus-operator-patches/06_ocp_manager_resources.diff
Labels: approved, dco-signoff: yes

#743 RBAC permissions for the deployment from source
  pelorus-operator/Dockerfile
  pelorus-operator/Makefile
  pelorus-operator/bundle.Dockerfile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/bundle/metadata/annotations.yaml
  pelorus-operator/bundle/tests/scorecard/config.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/rbac/pelorus_manager_role.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/config/scorecard/patches/basic.config.yaml
  pelorus-operator/config/scorecard/patches/olm.config.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
Labels: approved, dco-signoff: yes

#744 Update resources for the manager
  scripts/pelorus-operator-patches/06_ocp_manager_resources.diff
Labels: dco-signoff: yes

#747 Thanos rbac for the pelorus-operator
  scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
Labels: approved, dco-signoff: yes

#748 New pelorus operator version 0.0.9
  pelorus-operator/Dockerfile
  pelorus-operator/Makefile
  pelorus-operator/bundle.Dockerfile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/bundle/metadata/annotations.yaml
  pelorus-operator/bundle/tests/scorecard/config.yaml
  pelorus-operator/config/default/manager_auth_proxy_patch.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manager/manager.yaml
  pelorus-operator/config/rbac/pelorus_manager_role.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/config/scorecard/patches/basic.config.yaml
  pelorus-operator/config/scorecard/patches/olm.config.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
Labels: dco-signoff: yes

#746 Fix pelorus operator script to add proper instructions and remove dup
  scripts/create_pelorus_operator
Labels: approved, dco-signoff: yes

#750 Pelorus community operator fixes
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  charts/pelorus/subcharts/exporters/templates/exporters.yaml
  charts/pelorus/values.yaml
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/charts.pelorus.konveyor.io_pelorus.yaml
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/exporters.yaml
  pelorus-operator/helm-charts/pelorus/values.yaml
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
  scripts/pelorus-operator-patches/07_spec_description.diff
Labels: approved, dco-signoff: yes

#749 Deserialization: allow retaining source, fix getitem handling
  exporters/pelorus/deserialization/__init__.py
  exporters/pelorus/deserialization/errors.py
  exporters/pelorus/utils/__init__.py
  exporters/pelorus/utils/nested.py
  exporters/requirements.txt
  exporters/tests/test_deserialization.py
  exporters/tests/test_utils.py
Labels: lgtm, dco-signoff: yes

#752 Pelorus Operator v0.0.1 - Community Operator candidate
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  scripts/create_pelorus_operator
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
  scripts/pelorus-operator-patches/07_spec_description.diff
Labels: dco-signoff: yes
