Repository dora-metrics/pelorus, pull requests merged in 2022-05, with the labels that each got.

#405 Remove duplicate charts values.yaml file
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/values.yaml
Labels: approved

#449 Fix issue #448 to make handling of shell env vars consistently
  exporters/pelorus/__init__.py
  exporters/pelorus/utils.py
  exporters/tests/test_pelorus.py
  exporters/tests/test_utils.py
Labels: enhancement, mvr

#461 Fix Issue #446 where committime exporter had to be restarted
  exporters/committime/collector_base.py
  exporters/tests/integration/test_committime.py
Labels: mvr

#453 Fix JIRA query string to accept project FIRST and allow more then one project
  exporters/failure/app.py
  exporters/failure/collector_jira.py
  exporters/tests/test_failure_exporter.py
Labels: enhancement, jira, mvr

#442 Sample app todo
  samples/README.md
  samples/basic-nginx/.applier/group_vars/seed-hosts.yml
  samples/basic-nginx/.applier/hosts
  samples/basic-nginx/.openshift/builds/params
  samples/basic-nginx/.openshift/builds/template.yml
  samples/basic-nginx/.openshift/deployment/dev/params
  samples/basic-nginx/.openshift/deployment/prod/params
  samples/basic-nginx/.openshift/deployment/stage/params
  samples/basic-nginx/.openshift/deployment/template.yml
  samples/basic-nginx/.openshift/projects/projects.yml
  samples/basic-nginx/.openshift/rolebinding/pelorus/params
  samples/basic-nginx/.openshift/rolebinding/template.yml
  samples/basic-nginx/Jenkinsfile
  samples/basic-nginx/index.html
  samples/basic-nginx/nginx.conf
  samples/basic-nginx/requirements.yml
  samples/images/165596818-adc2469e-b3a6-4841-883f-e5018095801f.png
  samples/todolist.md
Labels: mvr

#445 Use ConfigMap as means for configuration
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/configmaps/committime.yaml
  charts/pelorus/configmaps/deploytime.yaml
  charts/pelorus/configmaps/failuretime.yaml
  charts/pelorus/configmaps/pelorus.yaml
  charts/pelorus/values.yaml
  docs/Configuration.md
  docs/Install.md
  exporters/committime/app.py
  exporters/deploytime/app.py
  exporters/failure/app.py
  exporters/failure/collector_servicenow.py
  exporters/pelorus/__init__.py
Labels: enhancement, mvr, lgtm

#467 Add readiness and liveness probes, associate exporter type label
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
Labels: lgtm

#457 Add a github failure exporter
  charts/pelorus/Chart.yaml
  charts/pelorus/configmaps/failuretime.yaml
  docs/Configuration.md
  exporters/failure/README.md
  exporters/failure/app.py
  exporters/failure/collector_github.py
  exporters/failure/collector_jira.py
  exporters/failure/collector_servicenow.py
  exporters/pelorus/utils.py
  exporters/requirements.txt
  exporters/tests/data/github_issue.json
  exporters/tests/data/github_labels.json
  exporters/tests/test_failure_exporter.py
  exporters/tests/test_pelorus.py
Labels: lgtm
