Repository dora-metrics/pelorus, pull requests merged in 2022-03, with the labels that each got.

#393 Release drafter action
  .github/workflows/release-drafter.yaml
Labels: maintenance

#377 rename redhat-cop to konveyor where appropriate
  CONTRIBUTING.md
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/values.yaml
  charts/pelorus/values.yaml
  docs/Configuration.md
  docs/Development.md
  docs/Install.md
  docs/dashboards/SoftwareDeliveryPerformance.md
  exporters/tests/test_exporters.py
  labs/consultant/02-Installation.md
  labs/consultant/03-Exporters.md
Labels: docs, maintenance

#397 Fix find in clean-dev-env for macOS
  Makefile
Labels: lgtm

#399 New minor release of Pelorus - requires OpenShift >= 4.7
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  docs/Install.md
Labels: lgtm

#398 Fix and update links in MinIO
  docs/MinIO.md
Labels: lgtm

#401 Easy release process
  Makefile
  docs/Development.md
  scripts/create_release_pr
Labels: lgtm, approved
