Repository dora-metrics/pelorus, pull requests merged in 2022-11, with the labels that each got.

#699 Add system-level doc dependencies to dev-env setup
  Makefile
Labels: lgtm, dco-signoff: yes

#700 fix: Update documentation index file
  README.md
  docs/index.md
Labels: needs-ok-to-test, dco-signoff: yes

#634 Config overhaul
  exporters/committime/__init__.py
  exporters/committime/app.py
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_base.py
  exporters/committime/collector_bitbucket.py
  exporters/committime/collector_gitea.py
  exporters/committime/collector_github.py
  exporters/committime/collector_gitlab.py
  exporters/committime/collector_image.py
  exporters/deploytime/app.py
  exporters/extra/releasetime/collector_github.py
  exporters/failure/app.py
  exporters/failure/collector_base.py
  exporters/failure/collector_github.py
  exporters/failure/collector_jira.py
  exporters/failure/collector_servicenow.py
  exporters/pelorus/__init__.py
  exporters/pelorus/config/README.md
  exporters/pelorus/config/converters.py
  exporters/pelorus/config/env_var_names.py
  exporters/pelorus/utils.py
  exporters/tests/integration/test_committime.py
  exporters/tests/test_deploytime.py
  exporters/tests/test_failure_exporter.py
  exporters/tests/test_pelorus.py
Labels: lgtm, approved, dco-signoff: yes

#704 use epoch vs. object for sn issue date
  exporters/failure/collector_base.py
  exporters/failure/collector_servicenow.py
Labels: approved, dco-signoff: no

#712 Update GH actions, cache python deps
  .github/workflows/build-pelorus.yaml
  .github/workflows/chart-lint.yml
  .github/workflows/conftest.yaml
  .github/workflows/integration-tests.yml
  .github/workflows/mockoon-tests.yml
  .github/workflows/pre-release.yaml
  .github/workflows/prometheus-rules.yml
  .github/workflows/python-formatting.yml
  .github/workflows/python-linting.yml
  .github/workflows/release.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/unittests.yml
Labels: lgtm, approved, dco-signoff: yes

#709 Pin macOS oc version to 4.10, download ARM on ARM macs
  scripts/get_tool_dl_url.py
  scripts/install_dev_tools
Labels: approved, dco-signoff: yes

#710 Introduce the start of automatic type checking
  .github/workflows/typecheck.yml
  Makefile
  exporters/requirements-dev.txt
  scripts/pre-commit
Labels: dco-signoff: yes

#694 Fancy new homepage and restructured navigation
  docs/Architecture.md
  docs/Dashboards.md
  docs/Philosophy.md
  docs/img/pelorus-pattern-blue.png
  docs/index.md
  docs/philosophy/bridge_outcomes.md
  docs/philosophy/index.md
  docs/philosophy/outcomes/SoftwareDeliveryPerformance.md
  docs/philosophy/outcomes/index.md
  docs/philosophy/outcomes/platform_adoption.md
  docs/philosophy/pelorus.md
  docs/philosophy/problem.md
  docs/stylesheets/extra.css
  mkdocs.yml
  overrides/home.html
Labels: approved, dco-signoff: yes

#713 Appease type checker, make some test setup more correct, fix troubleshooting script
  exporters/pelorus/config/__init__.py
  exporters/tests/integration/test_bitbucket.py
  exporters/tests/integration/test_committime.py
  exporters/tests/openshift_mocks.py
  exporters/tests/test_deploytime.py
  exporters/tests/test_exporters.py
  scripts/troubleshooting/missing_labels.py
Labels: lgtm, approved, dco-signoff: yes

#714 Script to create new operator from already existing helm charts
  scripts/README.md
  scripts/create_pelorus_operator
  scripts/pelorus-operator-patches/01_podman_makefile_tool.diff
  scripts/pelorus-operator-patches/02_makefile_image_url.diff
  scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
Labels: approved, dco-signoff: yes

#725 azure-devops: fix url connection string
  exporters/committime/collector_azure_devops.py
  exporters/tests/test_exporters.py
Labels: lgtm, approved

#737 Fixed icon for the pelorus-operator
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
Labels: lgtm, approved, dco-signoff: yes
