Repository dora-metrics/pelorus, pull requests merged in 2022-06, with the labels that each got.

#466 Allow JIRA to define custom resolution field and search query
  docs/Configuration.md
  exporters/failure/app.py
  exporters/failure/collector_jira.py
  exporters/tests/test_failure_exporter.py
Labels: enhancement, jira, mvr

#484 Ensure curl backwards compatibility in e2e tests
  scripts/run-pelorus-e2e-tests
Labels: ci, lgtm

#487 Use PULL_NUMBER in e2e tests scripts
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#483 Minor release of Pelorus 1.6.0
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  docs/Install.md
Labels: minor

#490 add sample workflow for the failure exporter
  samples/README.md
  samples/images/change_failure_rate_1.png
  samples/images/github_issue_1.png
  samples/images/github_issue_1_close.png
  samples/images/github_issues_setup.png
  samples/images/issue_2_non_deployment.png
  samples/images/mean_time_to_restore.png
  samples/images/todolist_failure_restore_start.png
  samples/todolist_commit_deploy.md
  samples/todolist_failure_restore.md
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#501 Use PULL_NUMBER in e2e tests scripts
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#505 New scenario tests make targets
  Makefile
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#506 allow the github issue org to updated to optional org
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#502 remove oc apply configmaps from ci
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#520 Add install_dev_tools support for arm macs
  scripts/install_dev_tools
Labels: lgtm

#516 Move default labels from helm pelorus example values.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/templates/thanos-rbac.yaml
  charts/pelorus/values.yaml
Labels: lgtm

#517 Show logs from crashing pods for e2e tests
  scripts/run-pelorus-e2e-tests
Labels: ci, lgtm

#522 Rename GIT_USER and GIT_TOKEN to be consistent across exporters
  charts/pelorus/Chart.yaml
  charts/pelorus/configmaps/committime.yaml
  charts/pelorus/secrets/github_example.yaml
  docs/Configuration.md
  docs/Development.md
  exporters/committime/app.py
  exporters/pelorus/__init__.py
  exporters/tests/test_pelorus.py
  labs/consultant/03-Exporters.md
  mocks/README.md
  samples/todolist_commit_deploy.md
  scripts/run-pelorus-e2e-tests
Labels: committime-exporter, mvr, bd-1

#523 Use generic method to validate exporters in e2e tests
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#524 Update grafana to the newest available version from v4 channel
  charts/operators/Chart.yaml
  charts/operators/templates/grafana-subscription.yaml
Labels: compatibility, maintenance, lgtm

#521 Improve failure time exporter documentation
  docs/Configuration.md
Labels: docs, lgtm

#515 Fix the traceback if no commit sha is found
  exporters/committime/collector_base.py
Labels: committime-exporter, maintenance, lgtm

#525 only change values.yml ref: master to PR if repo is pelorus
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#528 craft an upstream support policy
  README.md
  docs/UpstreamSupport.md
Labels: lgtm
