Repository dora-metrics/pelorus, pull requests merged in 2022-10, with the labels that each got.

#677 clean up pv && pvc prior to execution
  demo/demo-tekton.sh
Labels: lgtm, approved, dco-signoff: yes

#680 Add back bitbucket API version 1.0 support.
  exporters/committime/__init__.py
  exporters/committime/collector_bitbucket.py
  exporters/tests/integration/conftest.py
  exporters/tests/integration/test_bitbucket.py
  mocks/bitbucket_cloud.json
Labels: lgtm, approved, dco-signoff: yes

#676 Add operator-sdk support to dev env, add release URL extraction python script
  scripts/get_github_dl_url.py
  scripts/install_dev_tools
Labels: lgtm, approved, dco-signoff: yes

#687 Fix git blame ignore file
  .git-blame-ignore-revs
Labels: lgtm, dco-signoff: yes

#689 Replace shell get_download_url_from_github_api function
  Makefile
  scripts/install_dev_tools
Labels: approved, dco-signoff: yes

#688 New hotfix release to cover fix for the bitbucket API 1.0
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  docs/Install.md
Labels: lgtm, dco-signoff: yes, patch

#691 Switch documentation to material theme for mkdocs
  Makefile
  docs/img/architecture.png
  docs/img/favicon.png
  docs/img/icon-white.png
  docs/img/logo-white.png
  docs/img/multi-cluster_architecture.png
  docs/requirements.txt
  docs/stylesheets/extra.css
  mkdocs.yml
  readthedocs.yaml
Labels: approved, dco-signoff: yes
