Repository dora-metrics/pelorus, pull requests merged in 2022-04, with the labels that each got.

#404 Remove python patch version check
  Makefile
  scripts/README.md
  scripts/python-version-check.py
Labels: lgtm, approved

#402 Disable fail-fast on all python github actions
  .github/workflows/integration-tests.yml
  .github/workflows/python-formatting.yml
  .github/workflows/python-linting.yml
  .github/workflows/unittests.yml
Labels: lgtm, approved

#407 Improves workflow for building Pelorus images
  .github/workflows/build-pelorus.yaml
Labels: lgtm, approved

#406 Cleanup and documentation of the python requirements
  exporters/requirements-dev.txt
  exporters/requirements.txt
Labels: approved

#395 Extract image SHAs from status.containerStatuses as well as spec.containers
  exporters/deploytime/app.py
  exporters/tests/openshift_mocks.py
  exporters/tests/test_deploytime.py
Labels: enhancement, lgtm, approved

#408 Make chart-lint github action trigger on changes to requirements-dev.txt
  .github/workflows/chart-lint.yml
Labels: approved

#411 Better missing attribute errors
  exporters/committime/__init__.py
  exporters/committime/collector_base.py
  exporters/pelorus/utils.py
  exporters/tests/test_utils.py
Labels: lgtm, approved

#418 More commit debug logs, exit Build inspection early if not yet ready
  exporters/committime/__init__.py
  exporters/committime/collector_base.py
  exporters/pelorus/__init__.py
  exporters/pelorus/utils.py
Labels: lgtm

#431 Fix issue #430 to allow running Mockoon container without SELinux
  scripts/run-mockoon-tests
Labels: ci

#441 Make exporters log version information on startup
  exporters/pelorus/__init__.py
Labels: enhancement, lgtm
