Repository dora-metrics/pelorus, pull requests merged in 2022-08, with the labels that each got.

#586 Fix traceback for unsupported git providers
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_base.py
  exporters/committime/collector_bitbucket.py
  exporters/committime/collector_gitea.py
  exporters/committime/collector_github.py
  exporters/committime/collector_gitlab.py
Labels: lgtm

#588 Mutually dependent auth params, switch comittime to pelorus.config
  exporters/committime/app.py
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_gitea.py
  exporters/committime/collector_gitlab.py
  exporters/pelorus/__init__.py
  exporters/tests/integration/test_committime.py
  pyproject.toml
Labels: lgtm

#587 update Tekton demo with optional build types
  Makefile
  demo/README.md
  demo/demo-tekton.sh
  demo/python-example/Dockerfile
  demo/tekton-demo-setup/02-project.yaml
  demo/tekton-demo-setup/03-build-and-deploy.yaml
Labels: lgtm

#593 Fix default FQDN for gitea committime collector.
  docs/Configuration.md
  exporters/committime/collector_gitea.py
Labels: lgtm

#599 minor release - 1.7.0
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
Labels: lgtm, minor

#596 Add more doc for binary blds and annotations
  demo/README.md
  docs/Configuration.md
Labels: docs, lgtm

#608 Documentation for different exporter installation methods
  docs/Configuration.md
  docs/Install.md
  scripts/create_release_pr
Labels: docs, lgtm

#471 GitHub deploy time (release) collector
  exporters/deploytime/__init__.py
  exporters/deploytime/app.py
  exporters/extra/README.md
  exporters/extra/__init__.py
  exporters/extra/releasetime/__init__.py
  exporters/extra/releasetime/app.py
  exporters/extra/releasetime/collector_github.py
  exporters/pelorus/__init__.py
  exporters/pelorus/config/README.md
  exporters/pelorus/config/converters.py
  exporters/pelorus/utils.py
  exporters/provider_common/__init__.py
  exporters/provider_common/github.py
  exporters/tests/test_deploytime.py
Labels: lgtm, feature

#610 Ensure mongo-persistent-scc is deleted in e2e tests
  scripts/run-pelorus-e2e-tests
Labels: lgtm

#607 JIRA configuration examples
  docs/Configuration.md
Labels: docs

#606 label and annotate s2i tekton build
  demo/demo-tekton.sh
  demo/tekton-demo-setup/02-project.yaml
  demo/tekton-demo-setup/03-build-and-deploy.yaml
Labels: lgtm

#605 Collect commit time based on the Image Label or annotation
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/rbac.yaml
  charts/pelorus/configmaps/committime.yaml
  docs/Configuration.md
  exporters/committime/README.md
  exporters/committime/__init__.py
  exporters/committime/app.py
  exporters/committime/collector_base.py
  exporters/committime/collector_image.py
  exporters/tests/integration/test_committime.py
Labels: feature

#604 Requests custom certs
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_bitbucket.py
  exporters/committime/collector_gitea.py
  exporters/committime/collector_github.py
  exporters/committime/collector_gitlab.py
  exporters/failure/collector_github.py
  exporters/failure/collector_servicenow.py
  exporters/pelorus/certificates.py
  exporters/pelorus/config/converters.py
  exporters/tests/certs/conftest.py
  exporters/tests/certs/test_custom_certs.py
  exporters/tests/certs/utils/__init__.py
  exporters/tests/certs/utils/certs.py
  exporters/tests/certs/utils/https.py
  mocks/commitexporter_github.json
Labels: lgtm

#612 Requests custom certs docs and charts
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  docs/Configuration.md
  exporters/committime/collector_gitlab.py
  exporters/extra/releasetime/collector_github.py
  exporters/pelorus/certificates.py
  exporters/tests/certs/conftest.py
  exporters/tests/certs/test_custom_certs.py
  exporters/tests/certs/utils/certs.py
  exporters/tests/certs/utils/https.py
Labels: lgtm

#611 Small doc update for noobaa to include namespace
  docs/Configuration.md
  docs/Noobaa.md
Labels: docs, lgtm

#616 Allow user to override github bug label
  charts/pelorus/Chart.yaml
  charts/pelorus/configmaps/failuretime.yaml
  exporters/failure/app.py
  exporters/failure/collector_github.py
  exporters/pelorus/__init__.py
Labels: lgtm, feature

#618 Add a link to CoC in readme
  README.md
Labels: docs, lgtm
