Repository dora-metrics/pelorus, pull requests merged in 2022-09, with the labels that each got.

#617 Update tekton to label committime on image for s2itekton
  demo/tekton-demo-setup/03-build-and-deploy.yaml
  exporters/committime/collector_image.py
Labels: committime-exporter, lgtm

#619 Ensure thanos uses same version across all required containers
  charts/pelorus/Chart.yaml
  charts/pelorus/templates/prometheus-cr.yaml
  charts/pelorus/templates/thanos-query.yml
  charts/pelorus/templates/thanos-store.yml
  charts/pelorus/values.yaml
  docs/Install.md
  docs/Noobaa.md
Labels: compatibility, lgtm

#624 Revert "modifying python example, number 1"
  demo/python-example/response.txt
Labels: lgtm

#623 ensure buildConfig in tekton uses specified git url
  demo/tekton-demo-setup/03-build-and-deploy.yaml
Labels: ci, do-not-merge/hold

#625 Use pylama for python linting
  .github/workflows/python-linting.yml
  Makefile
  exporters/requirements-dev.txt
  pylava.ini
  pyproject.toml
Labels: lgtm

#626 JIRA exporter coverage in e2e runs
  Makefile
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved, dco-signoff: yes

#627 Use quay.io images from migtools namespace
  .github/workflows/build-pelorus.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  charts/pelorus/values.yaml
  docs/Configuration.md
Labels: lgtm, dco-signoff: yes

#630 Fix id of the action used to build pelorus-releasetime-exporter
  .github/workflows/build-pelorus.yaml
Labels: dco-signoff: no

#631 minor release for new quay.io migtool image location.
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  docs/Install.md
Labels: minor, dco-signoff: yes

#628 Add option to enable Thanos in the e2e script
  Makefile
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved, dco-signoff: yes

#633 Make logging set up part of exporter startup, not import side effect
  exporters/committime/app.py
  exporters/deploytime/app.py
  exporters/extra/releasetime/app.py
  exporters/failure/app.py
  exporters/pelorus/__init__.py
  exporters/tests/test_config.py
Labels: lgtm, approved, dco-signoff: yes

#632 Fix to ensure scenario-2 are running different deployments
  Makefile
Labels: dco-signoff: yes

#629 Update to the Upstream Support, PR template
  .github/pull_request_template.md
  .github/release-drafter.yml
  docs/UpstreamSupport.md
Labels: lgtm, dco-signoff: yes

#615 Troubleshooting script
  exporters/pelorus/utils.py
  pyproject.toml
  scripts/troubleshooting/missing_labels.py
Labels: lgtm, approved, feature, dco-signoff: yes

#636 Pre-mvr release (1.8.1)
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  docs/Install.md
Labels: dco-signoff: yes, patch

#640 Add option to configure Prometheus retention
  charts/pelorus/Chart.yaml
  charts/pelorus/templates/prometheus-cr.yaml
  charts/pelorus/values.yaml
  docs/Install.md
Labels: lgtm, approved, dco-signoff: no

#647 verify both the app and pelorus w/ tekton
  demo/README.md
  demo/tekton-demo-setup/02-project.yaml
  demo/tekton-demo-setup/03-build-and-deploy.yaml
Labels: lgtm, approved, dco-signoff: yes

#648 Automate tekton subsequent runs, add timeout for git clone
  demo/demo-tekton.sh
  demo/tekton-demo-setup/03-build-and-deploy.yaml
Labels: lgtm, approved, dco-signoff: yes

#653 Revert "Report resource timestamp as metric timestamp"
  exporters/committime/collector_base.py
  exporters/failure/collector_base.py
Labels: lgtm, dco-signoff: no

#649 Add option to configure Prometheus maximum storage capacity
  charts/pelorus/Chart.yaml
  charts/pelorus/templates/prometheus-cr.yaml
  charts/pelorus/values.yaml
  docs/Install.md
Labels: lgtm, dco-signoff: yes

#637 Validation of Thanos data in e2e script
  scripts/run-pelorus-e2e-tests
Labels: approved, dco-signoff: yes

#661 Add script to view all grafana queries in the SDP dashboard
  scripts/view-grafana-queries.py
Labels: approved, dco-signoff: yes

#656 Bump grafana version to the newest one.
  charts/operators/Chart.yaml
  charts/operators/templates/grafana-subscription.yaml
  charts/operators/templates/installplan-approval-job.yaml
Labels: approved, dco-signoff: yes

#655 Pre-mvr release (1.8.2)
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  docs/Install.md
Labels: approved, dco-signoff: yes, patch

#664 timestamp timezone fix
  exporters/committime/__init__.py
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_bitbucket.py
  exporters/committime/collector_gitea.py
  exporters/committime/collector_github.py
  exporters/committime/collector_gitlab.py
  exporters/committime/collector_image.py
  exporters/deploytime/__init__.py
  exporters/deploytime/app.py
  exporters/failure/collector_base.py
  exporters/failure/collector_github.py
  exporters/failure/collector_jira.py
  exporters/failure/collector_servicenow.py
  exporters/pelorus/__init__.py
  exporters/pelorus/timeutil.py
  exporters/provider_common/github.py
  exporters/provider_common/openshift.py
  exporters/tests/test_datetime.py
  exporters/tests/test_exporters.py
  exporters/tests/test_failure_exporter.py
  exporters/tests/test_pelorus.py
Labels: lgtm, approved, dco-signoff: yes

#665 Allow to use EPOCH timestamp in the image annotation
  docs/Configuration.md
  exporters/committime/collector_image.py
  exporters/pelorus/timeutil.py
  exporters/tests/test_datetime.py
Labels: lgtm, approved, dco-signoff: yes

#666 update tekton to use epoch
  demo/README.md
  demo/tekton-demo-setup/03-build-and-deploy.yaml
  demo/tekton-demo-setup/tekton_demo_values.yaml
Labels: lgtm, dco-signoff: yes

#669 Split tekton demo.
  demo/demo-tekton.sh
  demo/tekton-demo-setup/01-new-project-request_template.yaml
  demo/tekton-demo-setup/02-project.yaml
  demo/tekton-demo-setup/02-tekton-operator.yaml
  demo/tekton-demo-setup/03-rbac-pipeline-role.yaml
  demo/tekton-demo-setup/04-service-account_template.yaml
  demo/tekton-demo-setup/05-build-and-deploy.yaml
Labels: lgtm, approved, dco-signoff: yes

#654 Adds continous metric to the deploytime
  exporters/deploytime/app.py
Labels: approved, do-not-merge/hold, dco-signoff: yes

#675 Tekton demo improvements
  demo/demo-tekton.sh
  demo/tekton-demo-setup/05-build-and-deploy.yaml
Labels: approved, dco-signoff: yes
