Repository dora-metrics/pelorus, pull requests merged in 2023-10, with the labels that each got.

#1084 Update OCP check script and upstream support with the prow changes
  README.md
  docs/UpstreamSupport.md
  scripts/check_openshift_version.py
Labels: approved, dco-signoff: yes

#1047 Fix various dev tool install issues, make shellcheck a required lint
  .github/workflows/shellcheck.yml
  Makefile
  scripts/get_tool_dl_url.py
  scripts/install_dev_tools.sh
Labels: lgtm, approved, dco-signoff: yes

#723 Introduce developer adoption outcome; add mathjax for rendering formulas
  docs/javascripts/mathjax.js
  docs/philosophy/outcomes/Overview.md
  docs/philosophy/outcomes/developer_adoption.md
  docs/philosophy/outcomes/platform_adoption.md
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: docs, lgtm, approved, dco-signoff: yes
