Repository dora-metrics/pelorus, pull requests merged in 2023-03, with the labels that each got.

#850 New release of Pelorus with new pelorus operator to fix #849
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
  docs/Development.md
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
Labels: dco-signoff: yes

#851 Fix for broken RBAC in the pelorus-operator 0.0.3
  charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
Labels: dco-signoff: yes

#843 feat: Add PagerDuty Failure Exporter
  docs/GettingStarted/Overview.md
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/index.md
  exporters/failure/app.py
  exporters/failure/collector_github.py
  exporters/failure/collector_pagerduty.py
  exporters/pelorus/errors.py
  exporters/pelorus/utils/__init__.py
  exporters/tests/__init__.py
  exporters/tests/test_failure_exporter.py
  exporters/tests/test_failure_exporter_app.py
  exporters/tests/test_failure_exporter_pager_duty.py
Labels: lgtm, approved, dco-signoff: yes

#836 Webhook exporter allowing Pelorus to work with push data model
  exporters/requirements-dev.txt
  exporters/requirements.txt
  exporters/tests/data/webhook_pelorus_committime.json
  exporters/tests/data/webhook_pelorus_deploytime.json
  exporters/tests/data/webhook_pelorus_failure_created.json
  exporters/tests/data/webhook_pelorus_failure_resolved.json
  exporters/tests/test_in_memory_metric.py
  exporters/tests/test_pelorus_base_plugin.py
  exporters/tests/test_pelorus_webhook.py
  exporters/tests/test_pelorus_webhook_handler.py
  exporters/tests/test_webhook_models.py
  exporters/webhook/README.md
  exporters/webhook/__init__.py
  exporters/webhook/app.py
  exporters/webhook/models/__init__.py
  exporters/webhook/models/pelorus_webhook.py
  exporters/webhook/plugins/__init__.py
  exporters/webhook/plugins/pelorus_handler.py
  exporters/webhook/plugins/pelorus_handler_base.py
  exporters/webhook/store/__init__.py
  exporters/webhook/store/in_memory_metric.py
Labels: approved, dco-signoff: yes

#859 Add GitHub Actions to build the webhook exporter
  .github/workflows/build-pelorus.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  docs/Development.md
Labels: approved, dco-signoff: yes

#863 Follow up fix for pr #859 - fix indentation for github action
  .github/workflows/release.yml
Labels: approved, dco-signoff: yes

#865 Update webhook port to 8080 to match other exporters
  exporters/webhook/app.py
Labels: approved, dco-signoff: yes

#870 Pelorus webhook exporter doc
  docs/Architecture.md
  docs/Development.md
  docs/GettingStarted/Examples.md
  docs/GettingStarted/configuration/ExporterWebhook.md
  exporters/webhook/README.md
  mkdocs.yml
Labels: approved, dco-signoff: yes

#866 feat: Add external Prometheus host config option
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/templates/prometheus-cr.yaml
  charts/pelorus/templates/prometheus-scrape-config-secret.yaml
  charts/pelorus/values.yaml
  demo/tekton-demo-setup/operator_tekton_demo_values.yaml.sample
  docs/GettingStarted/Installation.md
  docs/GettingStarted/configuration/PelorusCore.md
  scripts/pelorus-operator-patches/07_spec_description.diff
Labels: lgtm, approved, dco-signoff: yes

#871 Fix the webhook timestamp validator
  exporters/tests/test_in_memory_metric.py
  exporters/tests/test_webhook_models.py
  exporters/webhook/models/pelorus_webhook.py
Labels: lgtm, approved, dco-signoff: yes

#876 Template and the tooling for the ADRs
  .adr-dir
  docs/Development.md
  docs/adr/0001-record-architecture-decisions.md
  exporters/requirements-dev.txt
Labels: lgtm, approved, dco-signoff: yes

#869 Fix/operator form options
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/values.yaml
  docs/GettingStarted/configuration/PelorusCore.md
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
  scripts/pelorus-operator-patches/07_spec_description.diff
Labels: lgtm, approved, dco-signoff: yes

#886 release: Pelorus Operator version 0.0.5
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
  charts/pelorus/values.yaml
  docs/Development.md
  pelorus-operator/Dockerfile
  pelorus-operator/Makefile
  pelorus-operator/bundle.Dockerfile
  pelorus-operator/bundle/manifests/charts.pelorus.konveyor.io_pelorus.yaml
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/bundle/metadata/annotations.yaml
  pelorus-operator/bundle/tests/scorecard/config.yaml
  pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
  pelorus-operator/config/scorecard/patches/basic.config.yaml
  pelorus-operator/config/scorecard/patches/olm.config.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
  pelorus-operator/helm-charts/pelorus/templates/prometheus-cr.yaml
  pelorus-operator/helm-charts/pelorus/templates/prometheus-scrape-config-secret.yaml
  pelorus-operator/helm-charts/pelorus/values.yaml
  scripts/create_pelorus_operator
Labels: lgtm, approved, dco-signoff: yes

#891 Webhook exporter metrics route to be same as other exporters
  docs/GettingStarted/configuration/ExporterWebhook.md
  exporters/webhook/app.py
Labels: lgtm, approved, dco-signoff: yes

#901 fix: Small general fixes
  docs/GettingStarted/configuration/ExporterDeploytime.md
  docs/GettingStarted/configuration/PelorusExporters.md
  exporters/tests/test_webhook_models.py
  exporters/webhook/models/pelorus_webhook.py
Labels: lgtm, approved, dco-signoff: yes

#910 Add Code of Conduct for the Pelorus project.
  CODE_OF_CONDUCT.md
Labels: lgtm, approved

#911 fix: add PagerDuty e2e test
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved

#900 fix: Azure devops URL parser
  docs/Development.md
  docs/GettingStarted/configuration/ExporterCommittime.md
  exporters/committime/__init__.py
  exporters/committime/app.py
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_base.py
  exporters/failure/app.py
  exporters/requirements.txt
  exporters/tests/__init__.py
  exporters/tests/test_committime_exporter_app.py
  exporters/tests/test_exporters.py
  exporters/tests/test_failure_exporter.py
  exporters/tests/test_failure_exporter_app.py
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved, dco-signoff: yes

#896 repo: Change to dora-metrics organization
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
  demo/README.md
  demo/demo-tekton.sh
  demo/tekton-demo-setup/05-build-and-deploy.yaml
  demo/tekton-demo-setup/operator_tekton_demo_values.yaml.sample
  docs/Development.md
  docs/GettingStarted/Examples.md
  docs/GettingStarted/Installation.md
  docs/GettingStarted/Overview.md
  docs/GettingStarted/QuickstartTutorial.md
  docs/GettingStarted/configuration/ExporterCommittime.md
  docs/GettingStarted/configuration/ExporterDeploytime.md
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/GettingStarted/configuration/ExporterWebhook.md
  docs/GettingStarted/configuration/PelorusCore.md
  docs/GettingStarted/configuration/PelorusExporters.md
  docs/GettingStarted/configuration/ProductionBestPractice.md
  docs/UpstreamSupport.md
  docs/philosophy/outcomes/SoftwareDeliveryPerformance.md
  exporters/tests/test_exporters.py
  labs/consultant/02-Installation.md
  labs/consultant/03-Exporters.md
  mkdocs.yml
  mocks/README.md
  samples/todolist_commit_deploy.md
  samples/todolist_failure_restore.md
  scripts/chart-test.sh
  scripts/create_pelorus_operator
  scripts/create_release_pr
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
  scripts/pelorus-operator-patches/07_spec_description.diff
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved, dco-signoff: yes
