Repository dora-metrics/pelorus, pull requests merged in 2023-01, with the labels that each got.

#759 Fix/improve demo documentation
  docs/Configuration.md
  docs/Dashboards.md
  docs/Demo.md
  docs/Development.md
  docs/Install.md
  docs/Noobaa.md
  docs/UpstreamSupport.md
  docs/configuration2.md
  docs/index.md
  docs/philosophy/pelorus.md
  mkdocs.yml
  scripts/run-pelorus-e2e-tests
Labels: docs, lgtm, dco-signoff: yes

#767 Use Pelorus Operator as first-class citizen for our docs
  docs/Demo.md
  docs/Install.md
  docs/configuration2.md
  docs/img/1_operator_install_step.png
  docs/img/2_operator_install_step.png
  docs/img/3_operator_install_step.png
  docs/img/4_operator_install_step.png
  docs/img/5_operator_install_step.png
  docs/img/6_operator_install_step.png
  docs/img/7_operator_install_step.png
Labels: dco-signoff: yes

#761 fix: Documentation typos
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Architecture.md
  docs/Configuration.md
  docs/Development.md
  docs/Noobaa.md
  docs/index.md
  docs/philosophy/outcomes/SoftwareDeliveryPerformance.md
Labels: docs, lgtm, dco-signoff: yes

#771 Rework of doc menus and it's locations
  docs/Architecture.md
  docs/Development.md
  docs/GettingStarted/Examples.md
  docs/GettingStarted/Installation.md
  docs/GettingStarted/Overview.md
  docs/GettingStarted/QuickstartTutorial.md
  docs/GettingStarted/configuration/Noobaa.md
  docs/GettingStarted/configuration/PelorusCore.md
  docs/GettingStarted/configuration/PelorusExporters.md
  docs/GettingStarted/configuration/ProductionBestPractice.md
  docs/index.md
  docs/philosophy/BridgeOutcomes.md
  docs/philosophy/HowPelorusCanHelp.md
  docs/philosophy/Overview.md
  docs/philosophy/TheProblemToday.md
  docs/philosophy/outcomes/Overview.md
  docs/requirements.txt
  mkdocs.yml
Labels: dco-signoff: yes

#763 Fix/tekton demo
  demo/demo-tekton.sh
  demo/tekton-demo-setup/02-tekton-operator.yaml
Labels: lgtm, approved

#773 update sample pelorus instance config for tekton demo and README
  demo/README.md
  demo/deprecrated/demo.sh
  demo/tekton-demo-setup/operator_tekton_demo_values.yaml.sample
  demo/tekton-demo-setup/tekton_demo_values.yaml
Labels: docs, dco-signoff: yes

#766 fix: mockoon script failing silently
  .github/workflows/mockoon-tests.yml
  scripts/run-mockoon-tests
Labels: lgtm, dco-signoff: yes

#779 New Pelorus Core config doc
  docs/GettingStarted/configuration/PelorusCore.md
Labels: dco-signoff: yes

#776 Fix github label trace
  exporters/failure/collector_github.py
Labels: lgtm, dco-signoff: yes

#769 Feat/add examples to documentation
  Makefile
  docs/Architecture.md
  docs/Development.md
  docs/GettingStarted/Examples.md
  docs/GettingStarted/Overview.md
  docs/img/diagrams/generate_diagrams.py
  docs/img/diagrams/pelorus_deployment_steps.png
  docs/img/diagrams/pelorus_overview.png
  docs/requirements.txt
Labels: docs, lgtm, approved, dco-signoff: yes

#784 New layout for the exporter docs
  docs/Development.md
  docs/GettingStarted/configuration/ExporterCommittime.md
  docs/GettingStarted/configuration/ExporterDeploytime.md
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/GettingStarted/configuration/PelorusExporters.md
  mkdocs.yml
Labels: dco-signoff: yes

#774 Updates to tekton demo instructions as requested by Mateus
  demo/README.md
  docs/GettingStarted/QuickstartTutorial.md
Labels: docs, dco-signoff: yes

#781 bump python version check to 3.11
  .github/workflows/chart-lint.yml
  .github/workflows/integration-tests.yml
  .github/workflows/mockoon-tests.yml
  .github/workflows/python-formatting.yml
  .github/workflows/python-linting.yml
  .github/workflows/shellcheck.yaml
  .github/workflows/typecheck.yml
  .github/workflows/unittests.yml
  docs/Development.md
  scripts/python-version-check.py
Labels: docs, lgtm, dco-signoff: yes

#786 Pelorus Operator v0.0.2
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/charts.pelorus.konveyor.io_pelorus.yaml
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/bundle/metadata/properties.yaml
  pelorus-operator/config/crd/bases/charts.pelorus.konveyor.io_pelorus.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/watches.yaml
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
  scripts/pelorus-operator-patches/07_spec_description.diff
  scripts/pelorus-operator-patches/08_watches_dependent_resources.diff
Labels: lgtm, dco-signoff: yes

#787 Update of deps to the operator 0.0.2
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  scripts/pelorus-operator-patches/bundle-patches/01_prometheus_grafana_dependencies.diff
Labels: dco-signoff: yes

#785 fix: Improve Failure Exporter configuration documentation
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/GettingStarted/configuration/PelorusExporters.md
  docs/img/github_issue.png
  docs/img/jira_issue.png
Labels: lgtm, dco-signoff: yes

#789 Changes to the Deploy Time Exporter doc
  doc_update.exporters.diff
  docs/GettingStarted/configuration/ExporterDeploytime.md
Labels: docs, dco-signoff: yes

#791 Remove diff file that was commited by mistake
  doc_update.exporters.diff
Labels: dco-signoff: yes

#794 Changes to the Commit Time Exporter doc
  docs/GettingStarted/Overview.md
  docs/GettingStarted/configuration/ExporterCommittime.md
  docs/GettingStarted/configuration/ExporterDeploytime.md
  docs/GettingStarted/configuration/PelorusExporters.md
Labels: docs, dco-signoff: yes

#797 Add logic to the CI where the pod was not ready.
  scripts/run-pelorus-e2e-tests
Labels: approved, dco-signoff: yes

#799 Fix/improve exporter docs
  docs/GettingStarted/configuration/Noobaa.md
  docs/GettingStarted/configuration/PelorusCore.md
  docs/GettingStarted/configuration/PelorusExporters.md
Labels: docs, lgtm, approved, dco-signoff: yes

#798 Small format update to the exporter failure doc
  docs/GettingStarted/configuration/ExporterFailure.md
Labels: docs, dco-signoff: yes

#795 Production Best Practices doc rework
  docs/GettingStarted/configuration/PelorusCore.md
  docs/GettingStarted/configuration/ProductionBestPractice.md
Labels: docs, dco-signoff: yes

#770 fix: Update documentation home page (index) and docs menu
  docs/GettingStarted/Installation.md
  docs/GettingStarted/configuration/ProductionBestPractice.md
  docs/index.md
  mkdocs.yml
  overrides/home.html
Labels: docs, lgtm, approved, dco-signoff: yes

#812 Fix Demo link to work with the Konveyor demo
  .readthedocs.yaml
  mkdocs.yml
Labels: dco-signoff: yes

#814 Update OWNERS file to address #805
  OWNERS
Labels: approved, dco-signoff: yes

#818 fix: GitHub actions CI jobs files
  .github/workflows/build-pelorus.yml
  .github/workflows/chart-lint.yml
  .github/workflows/conftest.yml
  .github/workflows/pre-release.yml
  .github/workflows/python-formatting.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/shellcheck.yml
  .github/workflows/typecheck.yml
Labels: lgtm, approved, dco-signoff: yes

#757 fix: add more tests to deserialization
  exporters/pelorus/deserialization/__init__.py
  exporters/pelorus/utils/nested.py
  exporters/tests/test_deserialization.py
  pyproject.toml
Labels: lgtm, approved, needs-ok-to-test, dco-signoff: yes

#760 Mockoon tests for image collector
  exporters/tests/integration/conftest.py
  exporters/tests/integration/test_committime.py
  exporters/tests/integration/test_image.py
  mocks/commitexporter_github.json
  scripts/run-mockoon-tests
Labels: approved, dco-signoff: yes

#822 fix pytest tests dir config
  pyproject.toml
Labels: lgtm, approved, dco-signoff: yes

#824 fix: Tests config to run doctests and coverage right folders
  .coveragerc
  Makefile
  docs/Development.md
  exporters/requirements-dev.txt
  pyproject.toml
Labels: lgtm, dco-signoff: yes

#816 feat: CI job for checking documentation generation
  .github/workflows/doc-check.yml
  Makefile
  docs/Development.md
  docs/GettingStarted/Installation.md
  docs/UpstreamSupport.md
  docs/philosophy/BridgeOutcomes.md
  docs/philosophy/HowPelorusCanHelp.md
  docs/philosophy/Overview.md
Labels: lgtm, approved, dco-signoff: yes

#820 docs: Use description lists instead of tabs
  docs/GettingStarted/Installation.md
  docs/GettingStarted/QuickstartTutorial.md
  docs/GettingStarted/configuration/ExporterCommittime.md
  docs/GettingStarted/configuration/PelorusCore.md
  docs/GettingStarted/configuration/PelorusExporters.md
  docs/GettingStarted/configuration/ProductionBestPractice.md
Labels: lgtm, approved, dco-signoff: yes
