Repository dora-metrics/pelorus, pull requests merged in 2023-04, with the labels that each got.

#921 fix: Jira integration test
  exporters/tests/test_failure_exporter.py
Labels: lgtm, approved, dco-signoff: yes

#920 Build exporter images with the tag from updated _imagestream_from_image
  .github/workflow_templates/build_push_exporters/action.yml
  .github/workflows/build-pelorus.yml
Labels: lgtm, approved, dco-signoff: yes

#912 fix: PagerDuty e2e test
  Makefile
  docs/Development.md
  docs/UpstreamSupport.md
  exporters/tests/test_failure_exporter_app.py
  exporters/tests/test_failure_exporter_pager_duty.py
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved, dco-signoff: yes

#926 Add secret to secure payload for the webhook exporter
  docs/GettingStarted/configuration/ExporterWebhook.md
  exporters/tests/test_pelorus_webhook.py
  exporters/tests/test_pelorus_webhook_handler.py
  exporters/webhook/app.py
  exporters/webhook/models/pelorus_webhook.py
  exporters/webhook/plugins/pelorus_handler.py
  exporters/webhook/plugins/pelorus_handler_base.py
Labels: lgtm, approved, dco-signoff: yes

#929 Pelorus-Operator 0.0.6 with fresh patches and updated release scripts
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  Makefile
  charts/operators/Chart.yaml
  charts/pelorus/Chart.yaml
  charts/pelorus/subcharts/exporters/Chart.yaml
  charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
  docs/Development.md
  pelorus-operator/Dockerfile
  pelorus-operator/Makefile
  pelorus-operator/PROJECT
  pelorus-operator/bundle.Dockerfile
  pelorus-operator/bundle/manifests/charts.pelorus.dora-metrics.io_peloruses.yaml
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/bundle/metadata/annotations.yaml
  pelorus-operator/bundle/tests/scorecard/config.yaml
  pelorus-operator/config/crd/bases/charts.pelorus.dora-metrics.io_peloruses.yaml
  pelorus-operator/config/crd/kustomization.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/prometheus/monitor.yaml
  pelorus-operator/config/rbac/leader_election_role.yaml
  pelorus-operator/config/rbac/pelorus_editor_role.yaml
  pelorus-operator/config/rbac/pelorus_viewer_role.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/config/samples/charts_v1alpha1_pelorus.yaml
  pelorus-operator/config/samples/kustomization.yaml
  pelorus-operator/config/scorecard/patches/basic.config.yaml
  pelorus-operator/config/scorecard/patches/olm.config.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_buildconfig.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/subcharts/exporters/templates/_imagestream_from_image.yaml
  pelorus-operator/watches.yaml
  scripts/chart-test.sh
  scripts/create_pelorus_operator
  scripts/pelorus-operator-patches/01_podman_makefile_tool.diff
  scripts/pelorus-operator-patches/02_makefile_image_url.diff
  scripts/pelorus-operator-patches/03_pelorus_operators_roles.diff
  scripts/pelorus-operator-patches/04_pelorus_cluster_service_versions.diff
  scripts/pelorus-operator-patches/05_remove_auth_proxy_container.diff
  scripts/pelorus-operator-patches/06_ocp_manager_resources.diff
  scripts/pelorus-operator-patches/07_spec_description.diff
  scripts/pelorus-operator-patches/08_watches_dependent_resources.diff
  scripts/pelorus-operator-patches/bundle-patches/01_prometheus_grafana_dependencies.diff
Labels: lgtm, approved, dco-signoff: yes

#919 fix: Azure devops e2e test
  docs/Development.md
  docs/GettingStarted/configuration/ExporterCommittime.md
  docs/UpstreamSupport.md
  scripts/run-pelorus-e2e-tests
Labels: lgtm, approved, dco-signoff: yes

#944 fix: Remove unused files from project
  demo/deprecrated/demo.sh
  labs/consultant/02-Installation.md
  labs/consultant/03-Exporters.md
  samples/README.md
  samples/images/165596818-adc2469e-b3a6-4841-883f-e5018095801f.png
  samples/images/change_failure_rate_1.png
  samples/images/github_issue_1.png
  samples/images/github_issue_1_close.png
  samples/images/github_issues_setup.png
  samples/images/issue_2_non_deployment.png
  samples/images/mean_time_to_restore.png
  samples/images/todolist_failure_restore_start.png
  samples/todolist_commit_deploy.md
  samples/todolist_failure_restore.md
Labels: lgtm, approved, dco-signoff: yes

#950 Pin azure-devops dependency due to it's new version issue
  exporters/requirements.txt
Labels: kind/bug, lgtm, approved, dco-signoff: yes

#830 fix: Add file extensions to all files
  .github/workflows/mockoon-tests.yml
  .github/workflows/python-formatting.yml
  .github/workflows/python-linting.yml
  .github/workflows/shellcheck.yml
  Makefile
  _test/bats-support-clone.sh
  _test/conftest.sh
  _test/test_prometheusrules.sh
  docs/Development.md
  docs/UpstreamSupport.md
  scripts/bump-version.py
  scripts/chart-check-and-bump.py
  scripts/chart-lint
  scripts/create_pelorus_operator.sh
  scripts/create_release_pr.sh
  scripts/e2e-tests-templates/build_binary_app.sh
  scripts/install_dev_tools.sh
  scripts/run-mockoon-tests.sh
  scripts/run-pelorus-e2e-tests.sh
Labels: dco-signoff: yes

#952 Enhance e2e script test to cover webhook exporter
  scripts/run-pelorus-e2e-tests.sh
Labels: lgtm, approved, dco-signoff: yes
