Repository dora-metrics/pelorus, pull requests merged in 2023-06, with the labels that each got.

#1004 fix: Use Containerfile instead s2i
  .github/workflow_templates/build_push_exporters/action.yml
  .github/workflows/build-pelorus.yml
  .github/workflows/test-images.yml
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/Development.md
  exporters/.dockerignore
  exporters/Containerfile
  exporters/pelorus/__init__.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_buildconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Labels: lgtm, approved, dco-signoff: yes

#1011 Add Timestamp to the Failure exporter
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  charts/pelorus/templates/prometheus-rules.yaml
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/GettingStarted/configuration/ExporterWebhook.md
  exporters/failure/collector_base.py
  exporters/webhook/app.py
  exporters/webhook/models/pelorus_webhook.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  pelorus-operator/helm-charts/pelorus/templates/prometheus-rules.yaml
Labels: lgtm, approved, dco-signoff: yes

#992 Skopeo exporter
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/GettingStarted/configuration/ExporterCommittime.md
  exporters/committime/app.py
  exporters/committime/collector_base.py
  exporters/committime/collector_containerimage.py
  exporters/provider_common/openshift.py
  exporters/tests/data/skopeo_custom_container_labels.json
  exporters/tests/data/skopeo_default_container_labels.json
  exporters/tests/data/skopeo_malformed_json_file.json
  exporters/tests/data/skopeo_missing_container_labels.json
  exporters/tests/httpd_docker_with_labels/Dockerfile
  exporters/tests/test_committime_exporter_containerimage.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Labels: kind/feature, lgtm, approved, dco-signoff: yes

#1013 fix: Restrict INFO log level verbosity
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/GettingStarted/configuration/ExporterCommittime.md
  docs/GettingStarted/configuration/ExporterDeploytime.md
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/GettingStarted/configuration/ExporterWebhook.md
  exporters/committime/collector_azure_devops.py
  exporters/committime/collector_base.py
  exporters/committime/collector_gitea.py
  exporters/deploytime/app.py
  exporters/failure/collector_azure_devops.py
  exporters/failure/collector_base.py
  exporters/failure/collector_github.py
  exporters/failure/collector_pagerduty.py
  exporters/failure/collector_servicenow.py
  exporters/provider_common/openshift.py
  exporters/tests/__init__.py
  exporters/tests/test_committime_exporter_app.py
  exporters/tests/test_failure_exporter_app.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Labels: lgtm, approved, dco-signoff: yes

#1014 feat: Add app hierarchy filter in Grafana
  _test/prometheus/test.yaml
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  charts/pelorus/templates/dashboard-sdp-byapp.yaml
  charts/pelorus/templates/dashboard-sdp.yaml
  charts/pelorus/templates/prometheus-rules.yaml
  docs/GettingStarted/configuration/PelorusExporters.md
  exporters/committime/collector_base.py
  exporters/deploytime/app.py
  exporters/failure/collector_base.py
  exporters/provider_common/__init__.py
  exporters/tests/test_in_memory_metric.py
  exporters/webhook/store/in_memory_metric.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  pelorus-operator/helm-charts/pelorus/templates/dashboard-sdp-byapp.yaml
  pelorus-operator/helm-charts/pelorus/templates/dashboard-sdp.yaml
  pelorus-operator/helm-charts/pelorus/templates/prometheus-rules.yaml
Labels: do-not-merge/hold, dco-signoff: yes

#1017 release: Pelorus Operator version 0.0.7
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/Development.md
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Labels: lgtm, approved, dco-signoff: yes
