Repository dora-metrics/pelorus, pull requests merged in 2023-05, with the labels that each got.

#940 fix: Release steps
  .github/ISSUE_TEMPLATE/release.yml
  .github/PULL_REQUEST_TEMPLATE/general_template.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  docs/GettingStarted/Overview.md
  docs/UpstreamSupport.md
Labels: docs, dco-signoff: yes

#962 fix: Choose PR template from UI
  .github/pull_request_template.md
Labels: dco-signoff: yes

#943 Ensure deploytime exporter accepts only valid timestamps
  docs/GettingStarted/configuration/ExporterDeploytime.md
  docs/GettingStarted/configuration/ExporterWebhook.md
  exporters/deploytime/app.py
  exporters/pelorus/timeutil.py
  exporters/tests/data/webhook_pelorus_committime.json
  exporters/tests/data/webhook_pelorus_deploytime.json
  exporters/tests/data/webhook_pelorus_failure_created.json
  exporters/tests/data/webhook_pelorus_failure_resolved.json
  exporters/tests/test_datetime.py
  exporters/tests/test_in_memory_metric.py
  exporters/tests/test_pelorus_base_plugin.py
  exporters/tests/test_pelorus_webhook.py
  exporters/tests/test_pelorus_webhook_handler.py
  exporters/tests/test_webhook_models.py
  exporters/webhook/README.md
  exporters/webhook/app.py
  exporters/webhook/models/pelorus_webhook.py
  exporters/webhook/plugins/pelorus_handler.py
Labels: approved, dco-signoff: yes

#968 fix: Version validation for exporters
  .github/workflows/chart-lint.yml
  .pre-commit-config.yaml
  scripts/chart-test.sh
Labels: lgtm, approved, fix, dco-signoff: yes

#971 fix: Add constrain to make chart-lint
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  scripts/chart-test.sh
  scripts/create_release_pr.sh
Labels: lgtm, approved, fix, dco-signoff: yes

#948 Feat: Create test images for PRs
  .github/workflow_templates/build_push_exporters/action.yml
  .github/workflow_templates/comment-pr/Dockerfile
  .github/workflow_templates/comment-pr/action.yml
  .github/workflow_templates/comment-pr/main.py
  .github/workflows/test-images.yml
  .github/workflows/trigger-test-images.yml
  docs/Development.md
  docs/requirements.txt
Labels: ci, dco-signoff: yes

#973 fix: New test image job
  .github/workflows/test-images.yml
Labels: dco-signoff: yes

#974 Fix/test image job env
  .github/workflows/test-images.yml
Labels: dco-signoff: yes

#976 fix: Custom action dockerfile
  .github/workflow_templates/comment-pr/Dockerfile
Labels: dco-signoff: yes

#977 fix: Custom action pydantic attribute name
  .github/workflow_templates/comment-pr/main.py
Labels: dco-signoff: yes

#972 test: Test new job
  .github/workflows/test-images.yml
  .github/workflows/trigger-test-images.yml
Labels: dco-signoff: yes

#883 fix: Worflows permissions to run integration tests
  .github/workflows/integration-tests.yml
Labels: dco-signoff: yes

#925 feat: Azure Boards (Azure DevOps issue tracker) support
  .github/workflows/chart-lint.yml
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/GettingStarted/Overview.md
  docs/GettingStarted/configuration/ExporterFailure.md
  docs/UpstreamSupport.md
  exporters/failure/app.py
  exporters/failure/collector_azure_devops.py
  exporters/pelorus/timeutil.py
  exporters/tests/test_failure_exporter_app.py
  exporters/tests/test_failure_exporter_azure_devops.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  scripts/run-pelorus-e2e-tests.sh
Labels: kind/feature, lgtm, approved, dco-signoff: yes

#963 Fix: Pin Python dependencies
  .github/dependabot.yml
  .github/workflows/check-python-dependencies.yml
  .readthedocs.yaml
  Makefile
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/Development.md
  docs/custom/home.html
  docs/requirements.txt
  exporters/requirements-dev.txt
  exporters/requirements.txt
  mkdocs.yml
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  poetry.lock
  pyproject.toml
  scripts/install_dev_tools.sh
Labels: fix, dco-signoff: yes, dependencies

#981 Rework of deploytime codebase
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/Development.md
  exporters/deploytime/app.py
  exporters/provider_common/openshift.py
  exporters/tests/openshift_mocks.py
  exporters/tests/test_commons_openshift.py
  exporters/tests/test_deploytime.py
  exporters/webhook/store/in_memory_metric.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Labels: lgtm, approved, dco-signoff: yes

#1001 fix: Update OpenShift versions
  .github/ISSUE_TEMPLATE/bug.yml
  .github/workflows/ci.yml
  Makefile
  README.md
  docs/UpstreamSupport.md
  scripts/check_openshift_version.py
Labels: approved, dco-signoff: yes

#998 feat: Add fallback option when Jira exporter can not determine application
  charts/operators/Chart.yaml
  charts/pelorus/Chart.lock
  charts/pelorus/Chart.yaml
  charts/pelorus/charts/exporters/Chart.yaml
  charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
  docs/GettingStarted/configuration/ExporterFailure.md
  exporters/failure/collector_jira.py
  exporters/tests/test_failure_exporter.py
  pelorus-operator/Makefile
  pelorus-operator/bundle/manifests/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/manager/kustomization.yaml
  pelorus-operator/config/manifests/bases/pelorus-operator.clusterserviceversion.yaml
  pelorus-operator/config/rbac/role.yaml
  pelorus-operator/helm-charts/pelorus/Chart.lock
  pelorus-operator/helm-charts/pelorus/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/Chart.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_deploymentconfig.yaml
  pelorus-operator/helm-charts/pelorus/charts/exporters/templates/_imagestream_from_image.yaml
Labels: lgtm, approved, dco-signoff: yes
